package jadecocoonwiki.saveeditor.saveeditor.minion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import jadecocoonwiki.saveeditor.helper.FormatterProvider;
import jadecocoonwiki.saveeditor.model.creature.Minion;

import javax.swing.*;
import javax.swing.text.NumberFormatter;
import java.awt.*;
import java.util.Optional;

public class MinionForm
{
    private final Optional<Minion> minionOptional;

    @SuppressWarnings("unused")
    private JPanel pnlMinionOne;

    private JFormattedTextField txtCurrentHP;
    private JFormattedTextField txtMaximumHP;
    private JFormattedTextField txtAttack;
    private JFormattedTextField txtDefense;
    private JFormattedTextField txtMagicAttack;
    private JFormattedTextField txtMagicDefense;
    private JFormattedTextField txtSpeed;

    public MinionForm(Optional<Minion> minionOptional)
    {
        this.minionOptional = minionOptional;
        $$$setupUI$$$();
    }

    private void createUIComponents()
    {
        NumberFormatter hpFormatter = FormatterProvider.getHPFormatter();
        NumberFormatter statsFormatter = FormatterProvider.getStatsFormatter();

        this.txtCurrentHP = new JFormattedTextField(hpFormatter);
        this.txtMaximumHP = new JFormattedTextField(hpFormatter);
        this.txtAttack = new JFormattedTextField(statsFormatter);
        this.txtDefense = new JFormattedTextField(statsFormatter);
        this.txtMagicAttack = new JFormattedTextField(statsFormatter);
        this.txtMagicDefense = new JFormattedTextField(statsFormatter);
        this.txtSpeed = new JFormattedTextField(statsFormatter);

        if (this.minionOptional.isPresent())
        {
            Minion minion = this.minionOptional.get();

            this.txtCurrentHP.setValue(minion.getCurrentHP());
            this.txtMaximumHP.setValue(minion.getMaximumHP());
            this.txtAttack.setValue(minion.getAttack());
            this.txtDefense.setValue(minion.getDefense());
            this.txtMagicAttack.setValue(minion.getMagicAttack());
            this.txtMagicDefense.setValue(minion.getMagicDefense());
            this.txtSpeed.setValue(minion.getSpeed());
        }
    }

    public Optional<Minion> getMinionOptional()
    {
        if (this.minionOptional.isPresent())
        {
            Minion minion = minionOptional.get();
            minion.setCurrentHP((Integer) txtCurrentHP.getValue());
            minion.setMaximumHP((Integer) txtMaximumHP.getValue());
            minion.setAttack((Short) txtAttack.getValue());
            minion.setDefense((Short) txtDefense.getValue());
            minion.setMagicAttack((Short) txtMagicAttack.getValue());
            minion.setMagicDefense((Short) txtMagicDefense.getValue());
            minion.setSpeed((Short) txtSpeed.getValue());
            return Optional.of(minion);
        }
        else
        {
            return Optional.empty();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        pnlMinionOne = new JPanel();
        pnlMinionOne.setLayout(new GridLayoutManager(8, 3, new Insets(8, 8, 8, 8), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Current HP");
        pnlMinionOne.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Maximum HP");
        pnlMinionOne.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Attack");
        pnlMinionOne.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Defense");
        pnlMinionOne.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Magic Attack");
        pnlMinionOne.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Magic Defense");
        pnlMinionOne.add(label6, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Speed");
        pnlMinionOne.add(label7, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pnlMinionOne.add(spacer1, new GridConstraints(0, 2, 7, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pnlMinionOne.add(spacer2, new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pnlMinionOne.add(txtCurrentHP, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtMaximumHP, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtAttack, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtDefense, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtMagicAttack, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtMagicDefense, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pnlMinionOne.add(txtSpeed, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return pnlMinionOne;
    }
}
