package jadecocoonwiki.saveeditor.saveeditor.misc;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import jadecocoonwiki.saveeditor.helper.FormatterProvider;
import jadecocoonwiki.saveeditor.model.misc.Miscellaneous;

import javax.swing.*;
import javax.swing.text.NumberFormatter;
import java.awt.*;

public class MiscForm
{
    private final Miscellaneous miscellaneous;

    @SuppressWarnings("unused")
    private JPanel pnlMisc;
    private JFormattedTextField txtMoney;

    public MiscForm(Miscellaneous miscellaneous)
    {
        this.miscellaneous = miscellaneous;
        $$$setupUI$$$();
    }

    private void createUIComponents()
    {
        NumberFormatter unsignedIntegerFormatter = FormatterProvider.getMoneyFormatter();

        this.txtMoney = new JFormattedTextField(unsignedIntegerFormatter);
        this.txtMoney.setValue(miscellaneous.getMoney());
    }

    public Miscellaneous getMisc()
    {
        this.miscellaneous.setMoney((Long) this.txtMoney.getValue());
        return this.miscellaneous;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        pnlMisc = new JPanel();
        pnlMisc.setLayout(new GridLayoutManager(2, 3, new Insets(8, 8, 8, 8), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Money");
        pnlMisc.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pnlMisc.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pnlMisc.add(spacer2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pnlMisc.add(txtMoney, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return pnlMisc;
    }
}
